services:
  # Service principal pour l'application web
  - type: web
    name: ncfd-app
    env: node
    runtime: node
    nodeVersion: 16
    buildCommand: yarn install --no-frozen-lockfile && yarn prisma:generate && node scripts/generate-config.js && NODE_OPTIONS=--openssl-legacy-provider yarn build
    startCommand: NODE_OPTIONS=--openssl-legacy-provider yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: MONGODB_URI
        value: "mongodb+srv://username:password@cluster.mongodb.net/ncfd" # À remplacer par votre URL MongoDB Atlas
      - key: PAYEER_ACCOUNT
        value: "" # À remplir dans l'interface Render
      - key: PAYEER_API_ID
        value: "" # À remplir dans l'interface Render
      - key: PAYEER_API_PASS
        value: "" # À remplir dans l'interface Render
      - key: PAYEER_M_SHOP
        value: "" # À remplir dans l'interface Render
      - key: PAYEER_KEY1
        value: "default_key1" # À remplacer par votre clé réelle
      - key: PAYEER_KEY2
        value: "default_key2" # À remplacer par votre clé réelle
      - key: DATABASE_URL
        fromDatabase:
          name: ncfd-db
          property: connectionString

  # Base de données PostgreSQL
databases:
  - name: ncfd-db
    plan: free
    ipAllowList: [] # permet l'accès public depuis n'importe où
